### ISSUE TITLE
Doesn't support dualshock analog on duckstation

### ISSUE THREAD

**Issue by kotenok2000** [ShendoXT/padtest#3]

**Comment by kotenok2000** [comment]
It didn't work on older version.

**Comment by ShendoXT** [comment]
Yeah. At first I thought that it's not working but but I haven't set up controller properly... Silly me.
So it's working as it should for you too on the newest version?

**Comment by kotenok2000** [comment]
Yes.

**Comment by ShendoXT** [comment]
Awesome :) Thanks for the input.
